<?php
$title = 'Edit User';
$this->headTitle($title);
?>
<?php $this->headStyle()->captureStart() ?>
    .fieldRow{
        margin:3px;
    }
    .labelBox{
        width:200px;
        float:left;
    }
    .fieldBox{
        margin:3px;
    }
<?php $this->headStyle()->captureEnd() ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post" action="">
    <div  style="clear:both;font-weight: bold;">
        <?php 
        if (isset($error_msg)) { 
            echo ($error_code ? 'Error code: ' . $error_code . '<br /> ' : '');
            echo ($error_msg ? 'Error Message: ' . $error_msg : '');
        } 
        ?>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Accounting Vendor:</div>
        <div class="fieldBox">
            <?php if (isset($user['accounting_vendor'])) echo $user['accounting_vendor'];?>&nbsp;
        </div>
    </div>
    
    <div class="fieldRow">
        <div class="labelBox">User Login:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="user_login" value="<?php echo $user['user_login'];?>"></div>
        </div>
    </div>
    
    <div class="fieldRow">
        <div class="labelBox">User Password:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="user_password" value=""></div>
        </div>
    </div>

    <div class="fieldRow">
        <div class="labelBox">Vendor Api Key:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="vendor_api_key" value="<?php echo !empty($user['property_list']['vendor_api_key']) ? $user['property_list']['vendor_api_key'] : '';?>"></div>
        </div>
    </div>
    
    <div class="fieldRow">
        <div class="labelBox">Vendor Password:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="vendor_password" value="<?php echo !empty($user['property_list']['vendor_password']) ? $user['property_list']['vendor_password'] : '';?>"></div>
        </div>
    </div>
    
    <div class="fieldRow">
        <div class="labelBox">Vendor Company Id:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="vendor_company_id" value="<?php echo !empty($user['property_list']['vendor_company_id']) ? $user['property_list']['vendor_company_id'] : '';?>"></div>
        </div>
    </div>
    
    <div class="fieldRow">
        <div class="labelBox">Property List:</div>
        <div class="fieldBox">
            &nbsp;
        </div>
    </div>
    <div class="fieldRow">
        <?php echo '<pre>'; print_r($user['property_list']); echo '</pre>';?>
    </div>
    <input type="submit" value="Submit">
</form>