<?php
$title = 'Add new Transaction';
$this->headTitle($title);
?>
<?php $this->headStyle()->captureStart() ?>
    .fieldRow{
        margin:3px;
    }
    .labelBox{
        width:200px;
        float:left;
    }
    .fieldBox{
        margin:3px;
    }
<?php $this->headStyle()->captureEnd() ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post" action="/transaction/add">
    <div class="fieldRow">
        <div class="labelBox">Company Id:</div>
        <div class="fieldBox">
            <select name="company_id">
                <option>Select</option>
                <?php foreach($companies as $company): ?>
                    <option value="<?php echo $company->getId(); ?>"><?php echo $company->getCompanyName(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Account Id:</div>
        <div class="fieldBox">
            <select name="account_id">
                <option>Select</option>
                <?php foreach($accounts as $account): ?>
                    <option value="<?php echo $account->getId(); ?>"><?php echo $account->getId(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Amount:</div>
        <div class="fieldBox"><input type="text" name="amount"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Currency:</div>
        <div class="fieldBox">
            <select name="currency">
                <option value="USD">USD</option>
                <option value="EURO">EURO</option>
            </select>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Tax Id:</div>
        <div class="fieldBox">
            <select name="tax_id">
                <option>Select</option>
                <?php foreach($taxes as $tax): ?>
                    <option value="<?php echo $tax->getId(); ?>"><?php echo $tax->getId(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div><input type="submit" value="Submit"></div>
</form>
