<?php
$title = 'Edit Transaction';
$this->headTitle($title);
?>
<?php $this->headStyle()->captureStart() ?>
    .fieldRow{
        margin:3px;
    }
    .labelBox{
        width:200px;
        float:left;
    }
    .fieldBox{
        margin:3px;
    }
<?php $this->headStyle()->captureEnd() ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post">
    <div class="fieldRow">
        <div class="labelBox">Company Id:</div>
        <div class="fieldBox">
            <select name="company_id">
                <option>Select</option>
                <?php foreach($companies as $company): ?>
                    <option value="<?php echo $company->getId(); ?>" <?php if ($company->getId() == $transaction->getCompanyId()) echo 'selected="selected"'?>><?php echo $company->getCompanyName(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Description:</div>
        <div class="fieldBox"><input type="text" name="description" value="<?php echo $transaction->getDescription();?>"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Account Id:</div>
        <div class="fieldBox">
            <select name="account_id">
                <option>Select</option>
                <?php foreach($accounts as $account): ?>
                    <option value="<?php echo $account->getId(); ?>" <?php if ($account->getId() == $transaction->getAccountId()) echo 'selected="selected"'?>><?php echo $account->getId(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Amount:</div>
        <div class="fieldBox"><input type="text" name="amount" value="<?php echo $transaction->getAmount()->getValue();?>"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Currency:</div>
        <div class="fieldBox">
            <select name="currency">
                <option value="USD" <?php if ('USD' == $transaction->getAmount()->getCurrency()) echo 'selected="selected"'?>>USD</option>
                <option value="EURO" <?php if ('EURO' == $transaction->getAmount()->getCurrency()) echo 'selected="selected"'?>>EURO</option>
            </select>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Tax Id:</div>
        <div class="fieldBox">
            <select name="tax_id">
                <option>Select</option>
                <?php foreach($taxes as $tax): ?>
                    <option value="<?php echo $tax->getId(); ?>" <?php if ($tax->getId() == $transaction->getTaxId()) echo 'selected="selected"'?>><?php echo $tax->getId(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

	<input type="submit" value="Submit">
</form>