<?php
$title = 'Add New Transaction';
$this->headTitle($title);
?>
<?php $this->headStyle()->captureStart() ?>
    .fieldRow{
        margin:3px;
    }
    .labelBox{
        width:200px;
        float:left;
    }
    .fieldBox{
        margin:3px;
    }
    .lineBox{
        float:left;
        width:140px;
    }
<?php $this->headStyle()->captureEnd() ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post" action="">
    <div  style="clear:both;font-weight: bold;">
        <?php 
        if (isset($error_msg)) { 
            echo ($error_code ? 'Error code: ' . $error_code . '<br /> ' : '');
            echo ($error_msg ? 'Error Message: ' . $error_msg : '');
        } 
        ?>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Customer Id:</div>
        <div class="fieldBox">
            <select name="customer_id">
                <option value="">Select</option>
                <?php foreach($customers as $customer): ?>
                    <option value="<?php echo $customer->getId(); ?>"><?php echo $customer->getCustomerName() . ' - uid' . $customer->getUserId(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Supplier Id:</div>
        <div class="fieldBox">
            <select name="supplier_id">
                <option value="">Select</option>
                <?php foreach($suppliers as $supplier): ?>
                    <option value="<?php echo $supplier->getId(); ?>"><?php echo $supplier->getSupplierName() . ' - uid' . $supplier->getUserId(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <?php
    if ($accountingVendor == 'Sage') {
    ?>
    <div class="fieldRow">
        <div class="labelBox">Amount:</div>
        <div class="fieldBox">
            <input type="text" name="amount"> <span style="font-size:10px;">(For Sage SalesReceipt, Purchase)</span>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Description:</div>
        <div class="fieldBox">
            <input type="text" name="transaction_description"> <span style="font-size:10px;">(For Sage SalesReceipt, Purchase)</span>
        </div>
    </div>
    <?php
    }
    ?>
    <div class="fieldRow">
        <div class="labelBox">Currency:</div>
        <div class="fieldBox">
            <select name="currency">
                <option value="">Select</option>
                <option value="USD">USD</option>
                <option value="EURO">EURO</option>
            </select>
        </div>
    </div>
    <?php
    if ($accountingVendor == 'Qb') {
    ?>
    <div class="fieldRow">
        <div class="labelBox">Tax Id:</div>
        <div class="fieldBox">
            <select name="tax_id">
                <option value="">Select</option>
                <?php foreach($taxes as $tax): ?>
                    <option value="<?php echo $tax->getId(); ?>"><?php echo $tax->getTaxCode() . ' - uid' . $tax->getUserId(); ?></option>
                <?php endforeach; ?>
            </select> <span style="font-size:10px;">(For Qb)</span>
        </div>
    </div>
    <?php
    }
    ?>
    <?php
    if ($accountingVendor == 'Qb') {
    ?>
    <div class="fieldRow">
        <div class="labelBox">Account Id Financial:</div>
        <div class="fieldBox">
            <select name="account_id_financial">
                <option value="">Select</option>
                <?php foreach($accountIdFinancials as $accountIdFinancial): ?>
                    <option value="<?php echo $accountIdFinancial->getId(); ?>"><?php echo $accountIdFinancial->getName() . ' - uid' . $accountIdFinancial->getUserId(); ?></option>
                <?php endforeach; ?>
            </select> <span style="font-size:10px;">(For Qb Purchase)</span>
        </div>
    </div>
    <?php
    } else if ($accountingVendor == 'Sage') {
    ?>
    <div class="fieldRow">
        <div class="labelBox">Bank Account:</div>
        <div class="fieldBox">
            <select name="bank_account_id">
                <option value="">Select</option>
                <?php foreach($bankAccounts as $bankAccount): ?>
                    <option value="<?php echo $bankAccount->getId(); ?>"><?php echo $bankAccount->getAccountName() . ' - ' . $bankAccount->getAccountNumber() . ' - uid' . $bankAccount->getUserId(); ?></option>
                <?php endforeach; ?>
            </select> <span style="font-size:10px;">(For Sage SalesReceipt, Purchase)</span>
        </div>
    </div>
    <?php
    }
    ?>
    <div class="fieldRow">
        <div class="labelBox">Payment Made:</div>
        <div class="fieldBox">
            <select name="payment_made">
                <option value="">Select</option>
                    <option value="1">Yes</option>
                    <option value="0">No</option>
            </select>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Payment Type:</div>
        <div class="fieldBox">
            <select name="payment_type">
                <option value="">Select</option>
                    <option value="Cash">Cash</option>
                    <option value="Check">Check</option>
            </select>
        </div>
    </div>
    <div style="clear:both">
        <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
        Sage: Not For Sage SalesReceipt, Purchase. Item or Account anyone can be selected for Invoice and Bill.
        <br />
        Qb: Item for Invoice and SalesReceipt, Account for Invoice and SalesReceipt
    </div>
    <br />
    <div class="fieldRow">
        <div class="lineBox">Account or Item</div>
        <div class="lineBox">Description</div>
        <div class="lineBox">Quantity</div>
        <div class="lineBox">Unit Price</div>
        <?php
        if ($accountingVendor == 'Sage') {
        ?>
        <div class="lineBox">Tax Percentage</div>
        <div class="lineBox">Discount Percentage</div>
        <div class="lineBox">Tax</div>
        <div class="lineBox">Discount</div>
        <?php
        }
        ?>
    </div>

    <?php
    for($k = 1; $k <= 3; $k++) {
    ?>
    <div style="clear:both"><p>&nbsp;</p></div>
    <div class="fieldRow">
        <div class="lineBox">
            <select name="account_id[<?php echo $k;?>]" style="width:140px;">
                <option value="">Account</option>
                <?php foreach($accounts as $account): ?>
                    <option value="<?php echo $account->getId(); ?>"><?php echo $account->getName() . ' (' . $account->getAccountType() . ') - uid' . $account->getUserId(); ?></option>
                <?php endforeach; ?>
            </select>
            <select name="item_id[<?php echo $k;?>]" style="width:140px;">
                <option value="">Item</option>
                <?php foreach($items as $item): ?>
                    <option value="<?php echo $item->getId(); ?>"><?php echo $item->getItemName() . ' (' . $item->getPrice() . ') - uid' . $item->getUserId(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="lineBox"><input type="text" name="description[<?php echo $k;?>]"></div>
        <div class="lineBox"><input type="text" name="quantity[<?php echo $k;?>]"></div>
        <div class="lineBox"><input type="text" name="unit_price[<?php echo $k;?>]"><span style="font-size:10px;">(Positive unit_price is Sale and negetive unit_price is Purchase)</span></div>
        <?php
        if ($accountingVendor == 'Sage') {
        ?>
        <div class="lineBox"><input type="text" name="tax_percentage[<?php echo $k;?>]"></div>
        <div class="lineBox"><input type="text" name="discount_percentage[<?php echo $k;?>]"></div>
        <div class="lineBox"><input type="text" name="tax[<?php echo $k;?>]"></div>
        <div class="lineBox"><input type="text" name="discount[<?php echo $k;?>]"></div>
        <?php
        }
        ?>
    </div>
    <?php
    }
    ?>
    
    <div style="clear:both">&nbsp;</div>
    <div class="fieldRow">
        <div class="lineBox">
            &nbsp;
        </div>
        <div class="lineBox">&nbsp;</div>
        <div class="lineBox">&nbsp;</div>
        <div class="lineBox">&nbsp;</div>
<!--        <div class="lineBox">&nbsp;&nbsp;&nbsp;Discount Amount</div>
        <div class="lineBox"><input type="text" name="discount_amount_total"></div>-->
        <div class="lineBox">&nbsp;</div>
        <div class="lineBox">&nbsp;</div>
        <div class="lineBox">Discount Percentage</div>
        <div class="lineBox"><input type="text" name="discount_percent_total"></div>
    </div>
    
    <div style="clear:both">&nbsp;</div>
    <div class="fieldRow">
        <div class="lineBox">
            &nbsp;
        </div>
        <div class="lineBox">&nbsp;</div>
        <div class="lineBox">&nbsp;</div>
        <div class="lineBox">&nbsp;</div>
        <div class="lineBox"><!--Tax Percentage-->&nbsp;</div>
        <div class="lineBox"><!--<input type="text" name="tax_percent_total">-->&nbsp;</div>
        <?php
        if ($accountingVendor == 'Sage') {
        ?>
        <div class="lineBox">Tax Amount</div>
        <div class="lineBox"><input type="text" name="tax_amount_total"></div>
        <?php
        } else {
        ?>
        <div class="lineBox">&nbsp;</div>
        <div class="lineBox">&nbsp;</div>
        <?php
        }
        ?>
    </div>
    
    
    <div style="clear:both"><p>&nbsp;</p></div>
    
    <div><input type="submit" value="Submit"></div>
</form>
