<?php
$title = 'Edit Customer';
$this->headTitle($title);
?>
<?php $this->headStyle()->captureStart() ?>
    .fieldRow{
        margin:3px;
    }
    .labelBox{
        width:200px;
        float:left;
    }
    .fieldBox{
        margin:3px;
    }
<?php $this->headStyle()->captureEnd() ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post" action="">
    <div  style="clear:both;font-weight: bold;">
        <?php 
        if (isset($error_msg)) { 
            echo ($error_code ? 'Error code: ' . $error_code . '<br /> ' : '');
            echo ($error_msg ? 'Error Message: ' . $error_msg : '');
        } 
        ?>
    </div>

    <div class="fieldRow">
        <div class="labelBox">Customer Name:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="customer_name" value="<?php echo $customer['customer_name'];?>"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Display Name:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="display_name" value="<?php echo $customer['display_name'];?>"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Name:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="name" value="<?php echo $customer['name'];?>"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Surname:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="surname" value="<?php echo $customer['surname'];?>"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Address 1:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="address1" value="<?php echo $customer['address1'];?>"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Address 2:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="address2" value="<?php echo $customer['address2'];?>"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">City:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="city" value="<?php echo $customer['city'];?>"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Postcode:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="postcode" value="<?php echo $customer['postcode'];?>"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Country:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="country" value="<?php echo $customer['country'];?>"></div>
        </div>
    </div>
    <input type="hidden" name="user_id" value="<?php echo $customer['user_id'];?>">
    <input type="submit" value="Submit">
</form>