<?php
$title = 'Add New Company';
$this->headTitle($title);
?>
<?php $this->headStyle()->captureStart() ?>
    .fieldRow{
        margin:3px;
    }
    .labelBox{
        width:200px;
        float:left;
    }
    .fieldBox{
        margin:3px;
    }
<?php $this->headStyle()->captureEnd() ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post" action="">
    <div  style="clear:both;font-weight: bold;">
        <?php 
        if (isset($error_msg)) { 
            echo ($error_code ? 'Error code: ' . $error_code . '<br /> ' : '');
            echo ($error_msg ? 'Error Message: ' . $error_msg : '');
        } 
        ?>
    </div>
<!--    <div class="fieldRow">
        <div class="labelBox">User Id:</div>
        <div class="fieldBox">
            <select name="user_id">
                <option value="">Select</option>
                <?php foreach($users as $user): ?>
                    <option value="<?php echo $user->getId(); ?>"><?php echo $user->getId() . ' - ' . $user->getUserLogin(); ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>-->
    <div class="fieldRow">
        <div class="labelBox">Company Type:</div>
        <div class="fieldBox">
            <select name="company_type">
                <option value="">Select</option>
                <option value="customer">Customer</option>
                <option value="vendor">Vendor</option>
            </select>
        </div>
    </div>

    <div class="fieldRow">
        <div class="labelBox">Company Name:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="company_name"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Display Name:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="display_name"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Name:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="name"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Surname:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="surname"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Address 1:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="address1"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Address 2:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="address2"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">City:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="city"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Postcode:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="postcode"></div>
        </div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Country:</div>
        <div class="fieldBox">
            <div class="fieldBox"><input type="text" name="country"></div>
        </div>
    </div>
    <div><input type="submit" value="Submit"></div>
</form>
