<?php
$title = 'Add new Company';
$this->headTitle($title);
?>
<?php $this->headStyle()->captureStart() ?>
    .fieldRow{
        margin:3px;
    }
    .labelBox{
        width:200px;
        float:left;
    }
    .fieldBox{
        margin:3px;
    }
<?php $this->headStyle()->captureEnd() ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post">
    <div class="fieldRow">
        <div class="labelBox">Vat Id:</div>
        <div class="fieldBox"><input type="text" name="vat_id"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Company Name:</div>
        <div class="fieldBox"><input type="text" name="company_name"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Display Name:</div>
        <div class="fieldBox"><input type="text" name="display_name"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Name:</div>
        <div class="fieldBox"><input type="text" name="name"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Surname:</div>
        <div class="fieldBox"><input type="text" name="surname"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Address:</div>
        <div class="fieldBox"><input type="text" name="address"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">City:</div>
        <div class="fieldBox"><input type="text" name="city"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Postcode:</div>
        <div class="fieldBox"><input type="text" name="postcode"></div>
    </div>
    <div class="fieldRow">
        <div class="labelBox">Country:</div>
        <div class="fieldBox"><input type="text" name="country"></div>
    </div>
    <div><input type="submit" value="Submit"></div>
</form>
