<?php $this->headStyle()->captureStart() ?>
.columnDiv{
    float:left;
    margin:3px;
    font-size: 12px;
}
.small{
    width:50px;
}
.medium{
    width:100px;
}
.big{
    width:150px;
}
<?php $this->headStyle()->captureEnd() ?>
<div>
    <div>
        <div>
            <div>
                <h3>Transaction Enrolled (Services)</h3>
            </div>
            <div>
                <div  style="clear:both;font-weight: bold;">
                    <?php 
                    if (isset($error_msg)) { 
                        echo ($error_code ? 'Error code: ' . $error_code . '<br /> ' : '');
                        echo ($error_msg ? 'Error Message: ' . $error_msg : '');
                    } 
                    ?>
                </div>
                <?php if (isset($services)) : ?>
                <div  style="clear:both;font-weight: bold;">
                        <div class="columnDiv big">Service Type</div>
                        <div class="columnDiv small">Id</div>
                        <div class="columnDiv big">Vendor Service Id</div>
                        <div class="columnDiv big">Transaction Id</div>
                        <div class="columnDiv big">Doc Number</div>
                        <div class="columnDiv big">Total Amount</div>
                        <div class="columnDiv big">&nbsp;</div>
                </div>
                <?php foreach($services as $service): ?>
                    <div style="clear:both">
                        <div class="columnDiv big"><?php echo $service['service_type']; ?></div>
                        <div class="columnDiv small"><?php echo $service['id']; ?></div>
                        <div class="columnDiv big"><?php echo $service['vendor_service_id']; ?></div>
                        <div class="columnDiv big"><?php echo $service['transaction_id']; ?></div>
                        <div class="columnDiv big"><?php echo $service['doc_number']; ?></div>
                        <div class="columnDiv big"><?php echo $service['total_amt']; ?></div>
                        <div class="columnDiv">
                            <a href="<?php echo $this->url(null, array('controller' => 'service', 'action'=>'view', 'id' => $service['id']));?>">View</a>
                        </div>
                    </div>
                <?php endforeach; ?>
                <?php endif; ?>
                <div style="clear:both"></div>
            </div>
        </div>
    </div>
</div>