<?php $this->headStyle()->captureStart() ?>
.columnDiv{
    float:left;
    margin:3px;
    font-size: 12px;    
}
.small{
    width:50px;
}
.medium{
    width:100px;
}
.big{
    width:150px;
}
<?php $this->headStyle()->captureEnd() ?>
<div>
    <div>
        <div>
            <div>
                <h3>Tax Rates</h3>
            </div>
            <div>
                <div  style="clear:both;font-weight: bold;">
                    <?php 
                    if (isset($error_msg)) { 
                        echo ($error_code ? 'Error code: ' . $error_code . '<br /> ' : '');
                        echo ($error_msg ? 'Error Message: ' . $error_msg : '');
                    } 
                    ?>
                </div>
                <?php if (isset($taxRates)) : ?>
                <div  style="clear:both;font-weight: bold;">
                        <div class="columnDiv big">Pluginto TaxRate Id</div>
                        <div class="columnDiv big">Tax Rate Name</div>
                        <div class="columnDiv big">Tax Rate Id</div>
                        <div class="columnDiv big">Rate Value</div>
                        <div class="columnDiv big">Tax Agency Id</div>
                        <div class="columnDiv big">Tax Applicable On</div>
                </div>
                <?php foreach($taxRates as $taxRate): ?>
                    <div style="clear:both">
                        <div class="columnDiv big"><?php echo $taxRate['id']; ?></div>
                        <div class="columnDiv big"><?php echo $taxRate['tax_rate_name']; ?></div>
                        <div class="columnDiv big"><?php echo $taxRate['tax_rate_id']; ?></div>
                        <div class="columnDiv big"><?php echo $taxRate['rate_value']; ?></div>
                        <div class="columnDiv big"><?php echo $taxRate['tax_agency_id']; ?></div>
                        <div class="columnDiv big"><?php echo $taxRate['tax_applicable_on']; ?></div>
                    </div>
                <?php endforeach; ?>
                <?php endif; ?>
                <div style="clear:both"></div>
            </div>
        </div>
    </div>
</div>